### ISSUE TITLE
全ページ共通のnav barのボタン間隔がばってる

### ISSUE THREAD

**Issue by yuzuka4573** [yuzuka4573/HI_HomePageRemakeAKB#3]
いうまでもないんだけど幅がバラバラで気持ち悪い、修正したいマン
ﾀｽｹﾃ

**Comment by defaultcf** [comment]
ボタンを使うのではなく，タブを使ったらどう？
https://getuikit.com/docs/tab

**Comment by yuzuka4573** [comment]
とりあえず修正したぞい（全ページ適用済み
